name: CI/CD Pipeline

# Trigger the workflow on push or pull request to main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to Docker Hub using provided credentials
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: sonathitharun
          password: dckr_pat_wZaJF_BOGwjTDE94IhYL7bJAbeg

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true # Change to true if you want to push the image to Docker Hub
          tags: sonathitharun/my-ci-cd-app:latest
